# Generated by Django 4.0.3 on 2022-03-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=40)),
                ('pais_origen', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('clasificacion', models.CharField(max_length=40)),
            ],
        ),
    ]
