# Generated by Django 4.0.3 on 2022-04-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='idioma',
        ),
        migrations.AddField(
            model_name='libros',
            name='creador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='cuerpo',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='libros',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
