# Generated by Django 4.0.3 on 2022-04-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega1', '0002_remove_libros_clasificacion_remove_libros_idioma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='isbn',
            new_name='id',
        ),
    ]
