# Generated by Django 4.0.3 on 2022-04-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega1', '0004_alter_libros_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='portada',
        ),
    ]
