# Generated by Django 4.0.3 on 2022-04-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega1', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
